config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index]
    resources :charges, only: [:new, :create]
    resources :images, only: [:create]
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admins#index'
    resources :users, :events
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :image

  validates :start_date,
            presence: true,
            numericality: { greater_than_or_equal_to: Time.now.to_i }

  validates :duration,
            presence: true, if: :mult_5_and_positive?

  validates :title,
            presence: true,
            length: { minimum: 5, maximum: 140 }

  validates :description,
            presence: true,
            length: { minimum: 20, maximum: 1000 }

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }

  validates :location,
            presence: true

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :organizer, class_name: 'User'

  def end_date
    self.start_date + self.duration * 60
  end

  private

  def mult_5_and_positive?
    return true if self.duration % 5 == 0 && self.duration > 0

    false
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController

    def index
      @events = Event.all
    end
    
    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :event_creator?, only: [:edit, :update]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @start_date = @event.start_date.to_date.strftime('%d %m %Y')
    @end_date = @event.end_date.to_date.strftime('%d %m %Y')
  end

  def new
  end

  def create
    @start_date = DateTime.strptime(params[:start_date], "%Y-%m-%d") 
    @event = Event.create(
      title: params[:title],
      description: params[:description],
      start_date: @start_date,
      duration: params[:duration],
      location: params[:location],
      price: params[:price].to_i,
      organizer: current_user
    )

    if @event.save
      flash[:success] = "Evènement créé avec succès"
      redirect_to @event 
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence 
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @start_date = DateTime.strptime(params[:start_date], "%Y-%m-%d")

    @event.update(
      start_date: @start_date,
      duration: params[:duration],
      location: params[:location],
      description: params[:description],
      title: params[:title],
      price: params[:price]
    )

    if @event.save
      redirect_to event_path(@event.id), notice: "Modification de l'événement effectuée"
    else
      p @event.errors.messages
      flash.now[:notice] = "Modification non prise en compte"
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to events_path, notice: "Suppression de l'événement effectuée"
    else
      flash.now[:notice] = "L'événement n'a pas pu être supprimé"
      render :edit
    end
  end

  private

  def event_creator?
    unless Event.find(params[:id]).organizer == current_user
      redirect_to events_path, notice: "Ce n'est pas votre événement"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def creator?(user, event)
    return true if event.organizer == user

    false
  end

  def on_the_list?(customer, event)
    invited = []
    event.attendances.each do |a|
      invited << a.user
    end
    return true if invited.include?(customer) 

    false
  end

end

app/views/admin/events/index.html.erb
<div class="container-fluid pt-3 pb-3 top-admin-event-title">
  <h1>Gestion des événements</h1>
</div>
<div class="container-fluid">
  <div class="row cols-2">
    <div class="col-2 pt-3 side-1">
      <%=link_to 'Gestion des utilisateurs', admin_root_path, class: "nav-link text-dark"%>
      <%=link_to 'Gestion des événements', admin_events_path, class: "nav-link text-dark"%>
    </div>
    <div class="col-10">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Titre</th>
            <th scope="col">Organisateur</th>
            <th scope="col">Date</th>
            <th scope="col">Durée</th>
            <th scope="col">Description</th>
            <th scope="col">Prix</th>
            <th scope="col">Opérations</th>
          </tr>
        </thead>
        <tbody>
          <%@events.each do |e|%>
            <tr>
              <th scope="row"><%=e.id%></th>
              <td><%=e.title%></td>
              <td><%=e.organizer.email%></td>
              <td><%=e.start_date.to_date%></td>
              <td><%=e.duration%></td>
              <td><%=e.description%></td>
              <td><%=e.price%></td>
              <td><%=link_to 'Opérations', admin_event_path(e.id), class: "btn btn-warning"%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>