config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index]
    resources :charges, only: [:new, :create]
    resources :images, only: [:create]
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admins#index'
    resources :users, :events
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  validates :encrypted_password,
            presence: true,
            length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/,
              message: 'email adress please'
            }
  
  has_many :attendances
  has_many :events, through: :attendances
  has_many :organised_events, foreign_key: 'organizer', class_name: 'Event'

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController

    def index
      @users = User.all
    end

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :auth_user?

  def show
    @user = current_user
  end

  private

  def auth_user?
    unless User.find(params[:id]) == current_user
      redirect_to events_path, notice: "Ce n'est pas votre profil !"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_admin?
    return true if user_signed_in? && current_user.is_admin == true
    
    false
  end
end

app/views/users/show.html.erb
<div class="jumbotron-fluid jumbo jumbo-profil text-center">
  <div class="layer"></div>
  <h1 class="display-1 text-light">Mon profil</h1>
  <div class="container" style="width: 8rem; height: 10rem;">
    <%if @user.avatar.attached?%>
      <div class="container avatar-image" style="background-image: url('<%=polymorphic_url(@user.avatar)%>');">
      </div>
    <%else%>
      <div class="container avatar-image default-avatar">
      </div>
    <%end%>
  </div>
</div>

<div class="container">
  <div class="row mt-5 cols-2">

    <div class="col">
      <div class="card">
        <div class="card-header">
          <h3>Mes infos</h3>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <strong>Email</strong> <p><%=current_user.email%></p> 
            </li>
            <li class="list-group-item">
              <strong>Prénom</strong> <p><%=current_user.first_name%></p> 
            </li>
            <li class="list-group-item">
              <strong>Nom</strong> <p><%=current_user.last_name%></p> 
            </li>
            <li class="list-group-item">
              <strong>Description</strong><br><p><%=current_user.description%></p> 
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card">
        <div class="card-header">
          <h3>Actions</h3>
        </div>
        <div class="card-body text-center">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <%=button_to 'Changer mon mot de passe', new_user_password_path(current_user.id), method: 'get', class: 'btn btn-primary'%>
            </li>
            <li class="list-group-item">
              <a href=<%=edit_user_registration_path%> class="btn btn-primary">Modifier mes infos</a>
            </li>
            <li class="list-group-item">
              <a href="#" class="btn btn-primary">Modifier ma description</a>
            </li>
            <li class="list-group-item">
              <a href="#" class="btn btn-primary">Modifier mon prénom</a>
            </li>
            <li class="list-group-item">
              <a href="#" class="btn btn-primary">Modifier mon nom</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container mt-5">
      <%current_user.organised_events.each do |o|%>
        <div class="card mt-3">
          <div class="card-header">
            <h3><%=o.title%></h3>
          </div>
          <div class="card-body">
            <%=button_to "Voir l'évènement", event_path(o.id), method: 'get', class: "btn btn-primary"%>
          </div>
        </div>
      <%end%>
    </div>

    <div class="container mt-4 mb-4">
      <%=form_with url: user_avatars_path(@user.id) do |f|%>
        <div class="form-group mb-3">
          <%=f.label :avatar, class: "h3"%>
          <%=f.file_field :avatar, class: "form-control"%>
        </div>
        <%=f.submit 'Ajouter', class: "btn btn-primary"%>
      <%end%>
    </div>

  </div>
</div>