config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index]
    resources :charges, only: [:new, :create]
    resources :images, only: [:create]
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admins#index'
    resources :users, :events
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :image

  validates :start_date,
            presence: true,
            numericality: { greater_than_or_equal_to: Time.now.to_i }

  validates :duration,
            presence: true, if: :mult_5_and_positive?

  validates :title,
            presence: true,
            length: { minimum: 5, maximum: 140 }

  validates :description,
            presence: true,
            length: { minimum: 20, maximum: 1000 }

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }

  validates :location,
            presence: true

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :organizer, class_name: 'User'

  def end_date
    self.start_date + self.duration * 60
  end

  private

  def mult_5_and_positive?
    return true if self.duration % 5 == 0 && self.duration > 0

    false
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController

    def index
      @events = Event.all
    end
    
    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :event_creator?, only: [:edit, :update]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @start_date = @event.start_date.to_date.strftime('%d %m %Y')
    @end_date = @event.end_date.to_date.strftime('%d %m %Y')
  end

  def new
  end

  def create
    @start_date = DateTime.strptime(params[:start_date], "%Y-%m-%d") 
    @event = Event.create(
      title: params[:title],
      description: params[:description],
      start_date: @start_date,
      duration: params[:duration],
      location: params[:location],
      price: params[:price].to_i,
      organizer: current_user
    )

    if @event.save
      flash[:success] = "Evènement créé avec succès"
      redirect_to @event 
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence 
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @start_date = DateTime.strptime(params[:start_date], "%Y-%m-%d")

    @event.update(
      start_date: @start_date,
      duration: params[:duration],
      location: params[:location],
      description: params[:description],
      title: params[:title],
      price: params[:price]
    )

    if @event.save
      redirect_to event_path(@event.id), notice: "Modification de l'événement effectuée"
    else
      p @event.errors.messages
      flash.now[:notice] = "Modification non prise en compte"
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to events_path, notice: "Suppression de l'événement effectuée"
    else
      flash.now[:notice] = "L'événement n'a pas pu être supprimé"
      render :edit
    end
  end

  private

  def event_creator?
    unless Event.find(params[:id]).organizer == current_user
      redirect_to events_path, notice: "Ce n'est pas votre événement"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def creator?(user, event)
    return true if event.organizer == user

    false
  end

  def on_the_list?(customer, event)
    invited = []
    event.attendances.each do |a|
      invited << a.user
    end
    return true if invited.include?(customer) 

    false
  end

end

app/views/events/_banner.html.erb
<div class="jumbotron-fluid text-center jumbo jumbo-huge jumbo-img img-center mb-5">
  <div class="container">
      <div class="jumbo-layer"></div>
      <h1 class="display-3">My Eventbrite</h1>
      <h3>Tous les événements de votre ville</h3>
      <p>Créez et participez aux événements de votre ville, devenez en un acteur incontournable !</p>
  </div>
</div> 

app/views/events/_event_card.html.erb
<div class="card my-4" >
  <%if @event.image.attached?%>
    <div class="card-header img-center" style="background-image: url('<%=polymorphic_url(@event.image)%>');">
    </div>
    <div class="card-body">
      <h5 class="card-title"><%=@event.title%></h5>
      <h6>Le 05/07/2021</h6>
      <p class="card-text">
        <%=@event.description%>
      </p>
      <%=link_to 'Voir', event_path(@event.id), class: 'btn-lg btn-primary'%>
    </div>
  <%else%>
    <div class="card-img-top img-center jumbo-event">
    </div>
    <div class="card-body">
      <h5 class="card-title"><%=@event.title%></h5>
      <h6>Le 05/07/2021</h6>
      <p class="card-text">
        <%=@event.description%>
      </p>
      <%=link_to 'Voir', event_path(@event.id), class: 'btn-lg btn-primary'%>
    </div>
  <%end%>
</div>

app/views/events/_event_organism.html.erb
<body>
<div class="container p-0 bg-light">
  <div class="container bg-dark my-5">
      <div class="row cols-2">
        <%if @event.image.attached?%>
          <div class="col-8 img-center" style="background-image: url('<%=polymorphic_url(@event.image)%>');">
          </div>
        <%else%>
          <div class="col-8 jumbo-event img-center">
          </div>
        <%end%>
          <div class="col-4 py-3">
            <h4>Date</h4>
            <p><%=@event.start_date.to_date%></p>
            <h4>Durée</h4>
            <p><%=@event.duration%> minutes</p>
            <h5>Organisé par</h5>
            <p><%=@event.organizer.email%></p>
            <h5>Nombre d'invités</h5>
            <p><%=@event.attendances.size%></p>
          </div>
      </div>
  </div>
  <div class="container bg-white p-4">
      <div class="row cols-2 align-items-center">
          <div class="col-10 px-5">
            <a class="text-dark mr-4" href=<%=user_path(current_user.id)%>><i class="fas fa-user"></i></a>
              <a class="text-dark" href="#"><i class="fas fa-share-alt"></i></a>
              <%if creator?(current_user, @event)%>
                <a class="btn-lg btn-primary ml-3" href=<%=event_attendances_path(@event.id)%>>Réservations</a>
              <%end%>
          </div>
          <div class="col-2">
            <%unless creator?(current_user, @event) || on_the_list(current_user, @event)%>
              <a class="btn-lg btn-warning" href=<%=new_event_charge_path(@event.id)%>>S'inscrire</a>
            <%else%>
              <button type="button" class="btn-lg btn-warning" disabled>S'inscrire</button>
            <%end%>
          </div>
      </div>
  </div>
  <div class="container">
      <div class="row cols-2 align-items-center">
          <div class="col-8 p-4 bg-dark">
              <h2>Description</h2>
              <p><%=@event.description%></p>
          </div>
          <div class="col-4 p-5">
              <div class="container text-right">
                  <ul class=" list-group list-group-flush">
                      <li class="list-group-item bg-primary">
                        <h5 class="mr-5"><%=@event.location%></h5>
                      </li>
                      <li class="list-group-item bg-primary">
                        <h5 class="mr-5"><%=@event.price%> €</h5>
                      </li>
                      <li class="list-group-item bg-primary">
                        <h5 class="mr-5">Le <%=@event.start_date.to_date%></h5>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
  <nav class="navbar justify-content-center bg-dark">
      <ul class="navbar nav">
          <li class="nav-item">
              <a href="https://fr-fr.facebook.com/" class="nav-link h3 text-white social"><i class="fab fa-facebook-square"></i></a>
          </li>
          <li class="nav-item">
              <a href="https://twitter.com/" class="nav-link h3 text-white social"><i class="fab fa-twitter"></i></a>
          </li>
          <li class="nav-item">
              <a href="https://www.instagram.com/" class="nav-link h3 text-white social"><i class="fab fa-instagram"></i></a>
          </li>
          <li class="nav-item">
              <a href="https://www.reddit.com/" class="nav-link h3 text-white social"><i class="fab fa-reddit-square"></i></a>
          </li>
      </ul>
  </nav>
</div>
</body>

app/views/events/_image_form.html.erb
<div class="container mt-4 mb-3">
  <%=form_with url: event_images_path(@event.id) do |f|%> 
    <div class="custom-file mb-3">
      <%=f.file_field :image, class: "custom-file-input" %>
      <%=f.label :image, 'Image', class: "custom-file-label"%>
    </div>
    <%=f.submit "Ajouter", class: "btn btn-primary"%>
  <%end%>
</div>

app/views/events/edit.html.erb
<div class="jumbotron-fluid text-center jumbo jumbo-modif-event">
  <div class="layer"></div>
  <h1 class="display-3 text-light">Modifier l'événement</h1>
</div>
<div class="container mt-5" style="width: 45rem;">
  <%=form_tag event_path(@event.id), method: 'patch' do%>
    <div class="form-group">
      <label class="h3">Titre</label>
      <%=text_field_tag 'title', @event.title, class: "form-control"%>
    </div>
    <div class="form-group">
      <label class="h3">Date</label>
      <%=date_field_tag 'start_date', @event.start_date.to_date, class: "form-control"%>
    </div>
    <div class="form-group">
      <label class="h3">Durée</label>
      <%=text_field_tag 'duration', @event.duration, class: "form-control"%>
    </div>
    <div class="form-group">
      <label class="h3">Description</label>
      <%=text_area_tag 'description', @event.description, class: "form-control"%>
    </div>
    <div class="form-group">
      <label class="h3">Prix</label>
      <%=text_field_tag 'price', @event.price, class: "form-control"%>
    </div>
    <div class="form-group mb-3">
      <label class="h3">Lieu</label>
      <%=text_field_tag 'location', @event.location, class: "form-control"%>
    </div>
    <div class="form-group d-flex">
      <%=submit_tag 'Modifier', class: "btn btn-primary"%>
      <%=button_to 'Supprimer',event_path(@event.id), method: 'delete', class: "btn btn-danger", style: "margin-left: 1rem;"%>
    </div>
  <%end%>
</div>

app/views/events/index.html.erb
<%=render 'banner'%>
<div class="container mt-5">
  <div class="row justify-content-center">
    <%@events.each do |e|%>
      <div class="col-4">
        <%@event = e%>
        <%=render partial: 'event_card', object: @event%>
      </div>
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
<div class="jumbotron-fluid text-center jumbo jumbo-create-event">
  <div class="layer"></div>
  <h1 class="display-3 text-light">Créer un évènement</h1>
  <h3 class="display-5 text-light">Lachez-vous !</h3>
</div>
<div class="container mt-5" style="width: 40rem;">
  <%=form_tag url_for(events_path), method: 'post' do%>

    <div class="form-group mt-4">
      <h3>
        <%= label_tag 'Titre'%>
      </h3>
      <%= text_field_tag 'title','', require: true, class: "form-control"%>
    </div>
    
    <div class="form-group mt-4">
      <h3>
        <%= label_tag 'Description' %>
      </h3>
      <%= text_area_tag 'description','', require: true, class: "form-control"%>
    </div>
    
    <div class="form-group mt-4">
      <h3>
        <%= label_tag 'Date de début' %>
      </h3>
      <%= date_field_tag 'start_date','', require: true, class: "form-control"%>
    </div>

    <div class="form-group mt-4">
      <h3>
        <%= label_tag 'Durée en minutes' %>
      </h3>
      <%= text_field_tag 'duration','', require: true, class: "form-control"%>
    </div>

    <div class="form-group mt-4">
      <h3>
        <%= label_tag 'Lieu' %>
      </h3>
      <%= text_field_tag 'location','', require: true, class: "form-control"%>
    </div>

    <div class="form-group mt-4">
      <h3>
        <%= label_tag 'Prix' %>
      </h3>
      <%= text_field_tag 'price','', require: true, class: "form-control"%>
    </div>
    
    <%= submit_tag "Créer", class: "btn btn-primary mt-4"%>
    
  <%end%>

</div>

app/views/events/show.html.erb
<%@object = @event%>
<%@page_title = @event.title%>
<%=render partial: 'layouts/banner', object: @object, locales: @page_title%>
<%=render partial: 'event_organism', object: @event%>

<%if creator?(current_user, @event)%>

  <%=render 'image_form', object: @event%>

<%end%>