config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index]
    resources :charges, only: [:new, :create]
    resources :images, only: [:create]
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admins#index'
    resources :users, :events
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  after_create :inscription_email

  validates :stripe_customer_id,
            presence: true

  belongs_to :user
  belongs_to :event

  private

  def inscription_email
    UserMailer.event_inscription_email(self.user, self.event).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :image

  validates :start_date,
            presence: true,
            numericality: { greater_than_or_equal_to: Time.now.to_i }

  validates :duration,
            presence: true, if: :mult_5_and_positive?

  validates :title,
            presence: true,
            length: { minimum: 5, maximum: 140 }

  validates :description,
            presence: true,
            length: { minimum: 20, maximum: 1000 }

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }

  validates :location,
            presence: true

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :organizer, class_name: 'User'

  def end_date
    self.start_date + self.duration * 60
  end

  private

  def mult_5_and_positive?
    return true if self.duration % 5 == 0 && self.duration > 0

    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  validates :encrypted_password,
            presence: true,
            length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/,
              message: 'email adress please'
            }
  
  has_many :attendances
  has_many :events, through: :attendances
  has_many :organised_events, foreign_key: 'organizer', class_name: 'Event'

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin/admins_controller.rb
module Admin
  class AdminsController < ApplicationController

    def index
      @users = User.all
    end

  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController

    def index
      @users = User.all
    end

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UsersHelper
  include EventsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate_user!

  def new
    @user = current_user
    @event = Event.find(params[:event_id])
    @amount = @event.price.to_i
  end

  def create
    # Amount in cents
    @user = current_user
    @event = Event.find(params[:event_id])
    @amount = @event.price

  begin
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount * 100,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    @attendance = Attendance.new(
      stripe_customer_id: charge.customer,
      user: @user,
      event: @event
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  if @attendance.save
    redirect_to event_path(params[:event_id]), notice: "Réservation enregistrée !"
  else
    flash.now[:notice] = "Problème lors de l'enregistrement"
    render :new
  end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :event_creator?, only: [:edit, :update]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @start_date = @event.start_date.to_date.strftime('%d %m %Y')
    @end_date = @event.end_date.to_date.strftime('%d %m %Y')
  end

  def new
  end

  def create
    @start_date = DateTime.strptime(params[:start_date], "%Y-%m-%d") 
    @event = Event.create(
      title: params[:title],
      description: params[:description],
      start_date: @start_date,
      duration: params[:duration],
      location: params[:location],
      price: params[:price].to_i,
      organizer: current_user
    )

    if @event.save
      flash[:success] = "Evènement créé avec succès"
      redirect_to @event 
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence 
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @start_date = DateTime.strptime(params[:start_date], "%Y-%m-%d")

    @event.update(
      start_date: @start_date,
      duration: params[:duration],
      location: params[:location],
      description: params[:description],
      title: params[:title],
      price: params[:price]
    )

    if @event.save
      redirect_to event_path(@event.id), notice: "Modification de l'événement effectuée"
    else
      p @event.errors.messages
      flash.now[:notice] = "Modification non prise en compte"
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to events_path, notice: "Suppression de l'événement effectuée"
    else
      flash.now[:notice] = "L'événement n'a pas pu être supprimé"
      render :edit
    end
  end

  private

  def event_creator?
    unless Event.find(params[:id]).organizer == current_user
      redirect_to events_path, notice: "Ce n'est pas votre événement"
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def create
        @event = Event.find(params[:event_id])
        @event.image.attach(params[:image])
        redirect_to event_path(@event)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :auth_user?

  def show
    @user = current_user
  end

  private

  def auth_user?
    unless User.find(params[:id]) == current_user
      redirect_to events_path, notice: "Ce n'est pas votre profil !"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def creator?(user, event)
    return true if event.organizer == user

    false
  end

  def on_the_list?(customer, event)
    invited = []
    event.attendances.each do |a|
      invited << a.user
    end
    return true if invited.include?(customer) 

    false
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_admin?
    return true if user_signed_in? && current_user.is_admin == true
    
    false
  end
end

app/views/admin/admins/index.html.erb
<div class="container-fluid pt-3 pb-3 top-admin-user-title">
  <h1>Gestion des utilisateurs</h1>
</div>
<div class="container-fluid">
  <div class="row cols-2">
    <div class="col-2 pt-3 side-1">
      <%=link_to 'Gestion des utilisateurs', admin_root_path, class: "nav-link text-dark"%>
      <%=link_to 'Gestion des événements', admin_events_path, class: "nav-link text-dark"%>
    </div>
    <div class="col-10">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Email</th>
            <th scope="col">Description</th>
            <th scope="col">Opérations</th>
          </tr>
        </thead>
        <tbody>
          <%@users.each do |u|%>
            <tr>
              <th scope="row"><%=u.id%></th>
              <td><%=u.first_name%></td>
              <td><%=u.last_name%></td>
              <td><%=u.email%></td>
              <td><%=u.description%></td>
              <td><%=link_to 'Opérations', admin_user_path(u.id), class: "btn btn-warning"%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<%object = @object%>
<%page_title = @page_title%>
<%if object.image.attached?%>
  <div class="jumbotron-fluid text-center jumbo jumbo-std img-center mb-5" style="background-image: url('<%=polymorphic_url(object.image)%>')"> 
    <div class="container">
        <div class="jumbo-layer"></div>
        <h1 class="display-3"><%=page_title%></h1>
    </div>
  </div> 
<%else%>
  <div class="jumbotron-fluid text-center jumbo jumbo-std jumbo-img img-center mb-5">
    <div class="container">
        <div class="jumbo-layer"></div>
        <h1 class="display-3"><%=page_title%></h1>
    </div>
  </div> 
<%end%>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid footer text-nowrap bottom bg-dark">
    <div class="row cols-3">
        <div class="col footer-list">
            <ul class="list-group-flush text-center">
                <li class="list-group-item">
                  <a href="#" class="text-white">L'équipe</a>
                </li>
                <li class="list-group-item">
                  <a href="#" class="text-white">Contacts</a>
                </li>
                <li class="list-group-item">
                    <a href="#" class="text-white">Besoin d'aide ?</a>
                </li>
            </ul>
        </div>
        <div class="col footer-list">
            <ul class="list-group-flush text-center">
                <li class="list-group-item">
                  <a href=<%=new_event_path%> class="text-white">Créer un événement</a>
                </li>
                <li class="list-group-item">
                    <a href="#" class="text-white">Gérer mes événements</a>
                </li>
                <li class="list-group-item">
                    <a href="#" class="text-white">Mes réservations</a>
                </li>
            </ul>
        </div>
        <div class="col footer-list">
            <ul class="list-group-flush text-center">
                <li class="list-group-item">
                  <a href="#" class="text-white">Mon profil</a>
                </li>
                <li class="list-group-item">
                  <a href="#" class="text-white">Se déconnecter</a>
                </li>
                <li class="list-group-item">
                    <a href="#" class="text-white">Mentions légales</a>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<body>
   <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href=<%=root_path%>>My Eventbrite</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href=<%=new_event_path%>>Créer un évènement</a>
              </li>
              <%if is_admin?%>
                <li>
                  <%=link_to 'Gestion du site', admin_root_path, class: "nav-link"%>
                </li>
              <%end%>
              <li class="nav-item dropdown">
                <%if user_signed_in?%>

                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Mon Profil
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href=<%=user_path(current_user.id)%>>Mon Profil</a></li>
                    <li><p><%=button_to 'Se déconnecter', destroy_user_session_path, :method => :delete, class: "dropdown-item"%></p></li>
                  </ul>

                <%else%>

                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    S'inscrire/se connecter
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href=<%=new_user_registration_path%>>S'inscrire</a></li>
                    <li><a class="dropdown-item" href=<%=new_user_session_path%>>Se connecter</a></li>
                  </ul>

                <%end%>

              </li>
            </ul>
          </div>
        </div>
      </nav>
      <% flash.each do | type, msg |%>
        <div class=<%="alert alert-#{type}"%>>
          <%= msg %>
        </div>
      <%end%>
    </header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%#Bootstrap%>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/darkly/bootstrap.min.css" integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  </head>

  <body>
    <%=render 'layouts/header'%>
    <%=render 'layouts/flash'%>

    <%= yield %>

    <%=render 'layouts/footer'%>
    <%#Bootstrap%>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </body>
</html>